### PR TITLE
feature/philipstv2016

### PR DESCRIPTION
**Pull request by skrollme**
Added the ability to control 2016 TV models

### CODE REVIEW

**Comment by Bankaifan** [comment]
When will this pull request be integrated into the base? ... Can't be that difficult :/
Very good work skrollme!

**Comment by maciboy** [comment]
I would appreciate an integration too :) 55POS901f

**Comment by PKonlinegithub** [comment]
I have a philips tv 55pus7272/12 (2017) and wol and the tv On command is not getting to action,
the request seems to be ok and get wol action back but it is not going On
The action tv standby is ok and ambilight on/off is also ok (thx to philips.py)
[10/15/2017, 2:41:23 PM] [TV] setPowerState - setting power state to on
[10/15/2017, 2:41:23 PM] [TV] setPowerState - WOL request done..
[10/15/2017, 2:41:23 PM] [TV] Excuting WakeOnLan request to 1C:5A:6B:CE:14:3B
[10/15/2017, 2:41:24 PM] [TV] setPowerState - WOL callback response: OK
[10/15/2017, 2:41:24 PM] [TV] setPowerState - powerstate attempt, attempt id:  8
[10/15/2017, 2:41:27 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  7
[10/15/2017, 2:41:30 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  6
[10/15/2017, 2:41:33 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  5
[10/15/2017, 2:41:36 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  4
[10/15/2017, 2:41:39 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  3
[10/15/2017, 2:41:42 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  2
[10/15/2017, 2:41:45 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  1
[10/15/2017, 2:41:48 PM] [TV] setPowerStateLoop - powerstate attempt, attempt id:  0
[10/15/2017, 2:41:51 PM] [TV] setPowerStateLoop - failed: ETIMEDOUT
[10/15/2017, 2:41:51 PM] [TV] setPowerStateLoop - ERROR: Error: HTTP attempt failed

Please somebody have a hit for me

**Comment by JustAnotherPU** [comment]
Could you please add it to the based plugin as for a docker in cannot replace files so the only way iI know is to install the plugins already updated with the new API, please fix it

**Comment by Bankaifan** [comment]
@skrollme  since this project seems to be dead, would you create a new GitHub-Project with your changes and refer to this one? Like it was done with homebridge-config-ui and homebridge-config-ui-x?

**Comment by skrollme** [comment]
@Bankaifan Done! I used the already existing fork. See: https://github.com/skrollme/homebridge-philipstv-x
It is also already published to npm: https://www.npmjs.com/package/homebridge-philipstv-x

**Pull request closed without merging**
